### ISSUE TITLE
create first release?

### ISSUE THREAD

**Issue by moustakas** [imcgreer/simqso#19]
@imcgreer thank you for all the recent changes.  Would you be willing to create a v1.0 tag and release of simqso so that my development in https://github.com/desihub/desisim/pull/293 can be done against a static version of your code?

**Comment by imcgreer** [comment]
I've already created development branches v1.0 and v1.1 before making major changes, so master is currently on v1.2. I'll create a tag v1.2.0 to reflect the current state of the code (the last set of modifications where the changes you requested).
