### ISSUE TITLE
Add option not to produce DLA in SIMQSO

### ISSUE THREAD

**Issue by londumas** [imcgreer/simqso#23]
There seems to be addition of DLAs in SIMQSO.
Is there a way to turn it on or off?
https://github.com/desihub/desisim/issues/327

**Comment by imcgreer** [comment]
The forest model can be arbitrarily defined. The default model is from Worseck & Prochaska (2011), which has the following distribution of absorbers as a function of column density and redshift:
https://github.com/imcgreer/simqso/blob/master/simqso/sqmodels.py#L30

Note the 'DLA' field. If you want to turn off DLAs, do something like this:
```
from simqso import sqmodels
forest = copy(sqmodels.WP11_model)
del forest['DLA']
```
