### ISSUE TITLE
package trying to read file not included in data

### ISSUE THREAD

**Issue by fjaviersanchez** [imcgreer/simqso#4]
Hi,

When I was trying to generate spectra like in the example I got the following error: `[Error] No such file or directory: data/VW01_Fe/Fe_UVOPT_V01_T06_BR92.asc`.

It looks like the folder `VW01_Fe` was removed in a previous commit but it is still used by the package.

Is there any workaround to this problem?

**Comment by imcgreer** [comment]
The problem is that the UV template is not publicly available -- it is supposed to be obtained directly from the authors of the original paper.

A simple workaround is to comment out the section labeled 'IronEmissionParams' in the example.

**Comment by imcgreer** [comment]
I have received permission to include the template in the code. Try to checkout the 'dev' branch -- it will now include iron emission. See 7be67d783089c3a7a3e10e92ba5ad52904ab37e8
